# Generated by Django 4.1.7 on 2023-06-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('abstraction', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='siteuser',
            name='interests',
            field=models.ManyToManyField(to='accounts.subject'),
        ),
    ]
