# Generated by Django 4.1.7 on 2023-06-26 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_delete_subject_alter_course_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
